name: Release Binary

on:
  push:
    tags:
      - 'v*'  # e.g. v1.0.0

permissions:
  contents: write 

jobs:
  build:
    name: Build and Upload Release Binary
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build release binary
        run: cargo build --release

      - name: Strip binary (optional)
        run: strip target/release/renamer

      - name: Create release asset
        run: |
          mkdir dist
          cp target/release/renamer dist/renamer-linux

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
